### ISSUE TITLE
Use full cluster names

### ISSUE THREAD

**Issue by petermattis** [cockroachlabs/roachprod#14]
The roachprod command line uses truncated table names: the full cluster name is whatever is specified on the command line prefixed with `<username>-`. This make it awkward to switch between use `crl-*` and `roachperf` (which use full cluster names) and `roachprod` (which uses the truncated names). 

I propose that `roachprod create` takes a full cluster name and we require it is prefixed with `<username>-`. `roachprod {destroy,extend}` should take a full cluster name.

**Comment by petermattis** [comment]
@mberhault I just ran into this confusion again last week. Any objections to my proposal?

**Comment by mberhault** [comment]
No objections whatsoever, I just haven't had a chance to poke at roachprod in a while. If someone wants to pick this up, they're welcome to.
