### ISSUE TITLE
Local SSD setup not working properly

### ISSUE THREAD

**Issue by a-robinson** [cockroachlabs/roachprod#17]
I followed the instructions on the README:
```
roachprod create rpc --lifetime=8h --nodes=6 --local-ssd
ssh-add ~/.ssh/google_compute_engine
crl-stage-binaries alex-rpc all scripts
crl-stage-binaries alex-rpc all local-cockroach
roachperf alex-rpc start
```

The last command just hangs forever on `alex-rpc: starting 1/6 \`. The logs on node 1 complain about the local SSD's permissions:

```
I171205 15:04:10.764070 14 storage/store.go:1198  [n1,s1] [n1,s1]: failed initial metrics computation: open /mnt/data1/lost+found: permission denied
E171205 15:04:10.764240 1 cli/error.go:104  cockroach server exited with error: could not query store capacity: open /mnt/data1/lost+found: permission denied
Error: cockroach server exited with error: could not query store capacity: open /mnt/data1/lost+found: permission denied
Failed running "start"
```

You could argue that this is a problem with `roachperf`'s choice of store directory/user more than `roachprod`, but I haven't changed my `roachperf` version lately (I did bump my `roachprod` version) and it used to work fine. Has anything changed here lately? Having to manually clean things up is annoying.

**Comment by mberhault** [comment]
Odd, one of the steps in the [startup script](https://github.com/cockroachlabs/roachprod/blob/master/utils.go) is `sudo chmod 777 /mnt/data1`. Could you check the permissions?

**Comment by a-robinson** [comment]
I've already fixed it, but I believe the issue was the permissions on `/mnt/data1/lost+found`, not on `/mnt/data1` itself. We could just throw in a `sudo rm -rf /mnt/data1/lost+found`.

**Comment by bdarnell** [comment]
`lost+found` is magic and could be recreated by `fsck` (I think). We may need to run in a subdirectory instead of directly on a filesystem root (if we can't tolerate the existence of files like this outside of our control. Skipping over it may be better).
