### ISSUE TITLE
Add SSH as an alias for ssh

### ISSUE THREAD

**Issue by awoods187** [cockroachlabs/roachprod#244]
Allow the all caps version of SSH to be acceptable in roachprod

**Comment by petermattis** [comment]
1. This is the wrong repo to file a roachprod issue now.
2. Why? `SSH` doesn't work on the command line. What you're asking for is very non-standard behavior, and thus requires a bit of justification.

**Comment by awoods187** [comment]
what's the right repo? 

I guess you can close this--it's a small thing i find mildly annoying but def not important

**Comment by petermattis** [comment]
https://github.com/cockroachdb/cockroach is the right repo for `roachprod` issues. This repo is defunct (and you shouldn't be using it to build `roachprod` anymore).

Do you really type `SSH` frequently? I'm super curious as unix convention is for lowercase commands and has been **forever**.
